In [4]:
import numpy as np
import random
from kesslergame import Scenario, GraphicsType, KesslerGame, TrainerEnvironment
from test_controller import TestController
import game
import time


In [5]:
my_test_scenario = Scenario(
    name="Test Scenario",
    # num_asteroids=5,
    asteroid_states=[
    {"position": (620, 510), "speed": -100, "angle": 0, "size": 4},
    # {"position": (620, 503), "speed": -50, "angle": 0, "size": 1},
    # {"position": (620, 505), "speed": -50, "angle": 0, "size": 1},
    # {"position": (620, 515), "speed": -50, "angle": 0, "size": 1},
    # {"position": (620, 530), "speed": -50, "angle": 0, "size": 1},
    # {"position": (620, 490), "speed": -50, "angle": 0, "size": 1},
    # {"position": (620, 480), "speed": -50, "angle": 0, "size": 1},
    ],
    ship_states=[
        {"position": (500, 500), "angle": 180, "lives": 3, "team": 4},
    ],
    map_size=(1000, 800),
    time_limit=99999,
    ammo_limit_multiplier=0,
    stop_if_no_ammo=False,
)

game_settings = {
    "perf_tracker": True,
    "graphics_type": GraphicsType.Tkinter,
    "realtime_multiplier": 1,
    "graphics_obj": None,
}
# Use this to visualize the game scenario


# game = KesslerGame(settings=game_settings)
game = TrainerEnvironment(settings=game_settings)  # Use this for max-speed, no-graphics simulation

pre = time.perf_counter()
score, perf_data = game.run(
    scenario=my_test_scenario, controllers=[TestController()]
    # scenario=my_test_scenario, controllers=[KeyboardController()]
    )

print("Scenario eval time: " + str(time.perf_counter() - pre))
print(score.stop_reason)
print("Asteroids hit: " + str([team.asteroids_hit for team in score.teams]))
print("Deaths: " + str([team.deaths for team in score.teams]))
print("Accuracy: " + str([team.accuracy for team in score.teams]))
print("Mean eval time: " + str([team.mean_eval_time for team in score.teams]))
print(
    "Evaluated frames: "
    + str([controller.eval_frames for controller in score.final_controllers])
)

Q-Values
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 

c:\Users\sambu\OneDrive\Desktop\SchoolSVN\F24\CS\CSP200\Fuzzifiers\branches\GAME\.venv\lib\site-packages\kesslergame\ship.py:205: RuntimeWarning: Ship 1 turn rate command outside of allowable range
  warnings.warn('Ship ' + str(self.id) + ' turn rate command outside of allowable range', RuntimeWarning)


Q-Values
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 

In [6]:
num_states = 1920 * 1080
num_actions = 4

# Define the Q-learning parameters
alpha = 0.1  # learning rate
gamma = 0.9  # discount factor
epsilon = 0.1  # exploration-exploitation trade-off


def select_action(state, epsilon):
    if np.random.rand() < epsilon:
        return np.random.choice(num_actions)  # exploration
    else:
        return np.argmax(Q[state, :])  # exploitation


In [ ]:


# Define the state and action spaces
num_states = 100   # discretized state space
num_actions = 4  # possible actions: turn right, turn left, move forward, move backward

# Initialize Q-values
Q = np.zeros((num_states, num_actions))

# Function to discretize the continuous state space
def discretize_state(continuous_state):
    # Example: simple discretization for demonstration purposes
    return int(continuous_state * num_states / (1920 * 1080))


# Simulate the game and update Q-values through Q-learning
num_episodes = 1000

for episode in range(num_episodes):
    # Initialize the game state
    state = discretize_state(0)

    # Iterate through time steps within the episode
    while not ship_state['']:
        # Select an action
        action = select_action(state)

        # Simulate the environment, get the next state and reward
        next_state, reward, game_over = simulate_environment(state, action)

        # Discretize the next state
        next_state = discretize_state(next_state)

        # Update the Q-value using the Q-learning update rule
        Q[state, action] = (1 - alpha) * Q[state, action] + \
                            alpha * (reward + gamma * np.max(Q[next_state, :]))

        # Move to the next state
        state = next_state

# After training, you can use the learned Q-values to play the game
# Example: Select the best action in a given state
best_action = np.argmax(Q[current_state, :])
